
FROM ubuntu:14.04
RUN rm /etc/apt/apt.conf.d/docker-gzip-indexes
sudo apt-get update
sudo apt-get -f install
# Install Ansible
RUN apt-get install -y software-properties-common git python-dev wget
RUN apt-get install -y python-pip
RUN pip install -U pip
RUN pip install ansible==1.9.4
RUN mkdir -p /etc/ansible

#COPY initctl_faker .
#RUN chmod +x initctl_faker && rm -fr /sbin/initctl && ln -s /initctl_faker /sbin/initctl

# Install Ansible inventory file
RUN echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts
