---
# handlers file for sa-box-staging

  - name: restart apache2
    service: name=apache2 state=restarted
    become: yes

  - name: restart fpm
    service: name=php5-fpm state=restarted
    become: yes
